### ISSUE TITLE
ClientAuthError: request_cannot_be_made: Token request cannot be made without authorization code or refresh token.

### ISSUE THREAD

**Issue by randomgithubuser1** [Azure-Samples/ms-identity-javascript-nodejs-desktop#5]
### This issue is for a: (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Follow setup instructions on readme.md

### Any log messages given by the failure

> electron-test-app@1.0.0 start
> electron App/Main.js
> 
> [Tue, 20 Apr 2021 22:17:23 GMT] :  : @azure/msal-node@1.0.0 : Info - getAuthCodeUrl called
> [Tue, 20 Apr 2021 22:17:23 GMT] :  : @azure/msal-node@1.0.0 : Verbose - initializeRequestScopes called
> [Tue, 20 Apr 2021 22:17:23 GMT] :  : @azure/msal-node@1.0.0 : Verbose - buildOauthClientConfiguration called
> [Tue, 20 Apr 2021 22:17:23 GMT] :  : @azure/msal-node@1.0.0 : Verbose - createAuthority called
> [Tue, 20 Apr 2021 22:17:23 GMT] :  : @azure/msal-node@1.0.0 : Verbose - Retrieving all cache keys
> [Tue, 20 Apr 2021 22:17:23 GMT] :  : @azure/msal-node@1.0.0 : Verbose - Getting cache key-value store
> [Tue, 20 Apr 2021 22:17:24 GMT] :  : @azure/msal-node@1.0.0 : Verbose - Getting cache key-value store
> [Tue, 20 Apr 2021 22:17:24 GMT] :  : @azure/msal-node@1.0.0 : Verbose - Setting cache key value store
> [Tue, 20 Apr 2021 22:17:24 GMT] :  : @azure/msal-node@1.0.0 : Verbose - Auth client config generated
> [Tue, 20 Apr 2021 22:17:42 GMT] :  : @azure/msal-node@1.0.0 : Info - acquireTokenByCode called
> [Tue, 20 Apr 2021 22:17:42 GMT] :  : @azure/msal-node@1.0.0 : Verbose - initializeRequestScopes called
> [Tue, 20 Apr 2021 22:17:42 GMT] :  : @azure/msal-node@1.0.0 : Verbose - buildOauthClientConfiguration called
> [Tue, 20 Apr 2021 22:17:42 GMT] :  : @azure/msal-node@1.0.0 : Verbose - createAuthority called
> [Tue, 20 Apr 2021 22:17:42 GMT] :  : @azure/msal-node@1.0.0 : Verbose - Retrieving all cache keys
> [Tue, 20 Apr 2021 22:17:42 GMT] :  : @azure/msal-node@1.0.0 : Verbose - Getting cache key-value store
> [Tue, 20 Apr 2021 22:17:42 GMT] :  : @azure/msal-node@1.0.0 : Verbose - Getting cache key-value store
> [Tue, 20 Apr 2021 22:17:42 GMT] :  : @azure/msal-node@1.0.0 : Verbose - Getting cache key-value store
> [Tue, 20 Apr 2021 22:17:42 GMT] :  : @azure/msal-node@1.0.0 : Verbose - Setting cache key value store
> [Tue, 20 Apr 2021 22:17:42 GMT] :  : @azure/msal-node@1.0.0 : Verbose - Auth client config generated
> [Tue, 20 Apr 2021 22:17:42 GMT] :  : @azure/msal-common@4.0.1 : Info - in acquireToken call
> (node:63536) UnhandledPromiseRejectionWarning: ClientAuthError: request_cannot_be_made: Token request cannot be made without authorization code or refresh token.
>     at ClientAuthError.AuthError [as constructor] (/Users/user/Downloads/ms-identity-javascript-nodejs-desktop-main/node_modules/@azure/msal-common/dist/index.js:398:24)
>     at new ClientAuthError (/Users/user/Downloads/ms-identity-javascript-nodejs-desktop-main/node_modules/@azure/msal-common/dist/index.js:634:28)
>     at Function.ClientAuthError.createTokenRequestCannotBeMadeError (/Users/user/Downloads/ms-identity-javascript-nodejs-desktop-main/node_modules/@azure/msal-common/dist/index.js:747:16)
>     at AuthorizationCodeClient.<anonymous> (/Users/user/Downloads/ms-identity-javascript-nodejs-desktop-main/node_modules/@azure/msal-common/dist/index.js:4364:51)
>     at step (/Users/user/Downloads/ms-identity-javascript-nodejs-desktop-main/node_modules/@azure/msal-common/dist/index.js:79:23)
>     at Object.next (/Users/user/Downloads/ms-identity-javascript-nodejs-desktop-main/node_modules/@azure/msal-common/dist/index.js:60:53)
>     at /Users/user/Downloads/ms-identity-javascript-nodejs-desktop-main/node_modules/@azure/msal-common/dist/index.js:53:71
>     at new Promise (<anonymous>)
>     at __awaiter (/Users/user/Downloads/ms-identity-javascript-nodejs-desktop-main/node_modules/@azure/msal-common/dist/index.js:49:12)
>     at AuthorizationCodeClient.acquireToken (/Users/user/Downloads/ms-identity-javascript-nodejs-desktop-main/node_modules/@azure/msal-common/dist/index.js:4357:16)
> (node:63536) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
> (node:63536) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

### Expected/desired behavior
> Demo should work

### OS and version?
> MacOS 10.15.7

### Mention any other details that might be useful
> I added all the required variables to the .env file.

**Comment by derisen** [comment]
@randomgithubuser1 can you share the content of your `.env` file as well?

**Comment by randomgithubuser1** [comment]
```# Credentials
CLIENT_ID=d4813e7a-15c9-41d3-bcde-1636bac17083
TENANT_ID=701edd3e-c7a8-4789-b1ce-8a243620d68f

# Configuration
REDIRECT_URI=msal://redirect

# Endpoints
AAD_ENDPOINT_HOST=https://login.microsoftonline.com/
GRAPH_ENDPOINT_HOST=https://graph.microsoft.com/

# RESOURCES
GRAPH_ME_ENDPOINT=v1.0/me
GRAPH_MAIL_ENDPOINT=v1.0/me/messages

# SCOPES
GRAPH_SCOPES=User.Read Mail.Read```

**Comment by derisen** [comment]
@randomgithubuser1 sorry, I can't reproduce this on my end. Can you also share your app manifest (Azure portal > your app registration > Manifest)?

**Comment by derisen** [comment]
Also, it would be a good idea to update the `@azure/msal-node` package to latest (1.0.1).

**Comment by derisen** [comment]
Closing due to inactivity. Let us know!
